### ISSUE TITLE
Loading initial state and hydrating.

### ISSUE THREAD

**Issue by jmatsushita** [salsita/redux-elm#32]
Hi there,

What's the pattern in redux-elm to hydrate/rehydrate which if I understand correctly is the redux terminology for providing initial state from the server or a store (in my case Pouch).

I'm not sure if I can do this in the boilerplate or if it should go in the Updaters and if so how?

Cheers,

Jun

**Comment by jmatsushita** [comment]
It seems maybe I should use something like https://github.com/KELiON/redux-async-initial-state ?

**Comment by tomkis1** [comment]
Hello,

the idea is pretty simple, you should be able to provide initial state in `boilerplate.js` [file located in the skeleton repo](https://github.com/salsita/redux-elm-skeleton/blob/master/src/boilerplate.js#L13).

So instead of 
```javascript
const store = storeFactory(updater);
```

You'd have something like:
```javascript
const store = storeFactory(updater, window.reduxState);
```

Where `window.reduxState` would just be serialized JSON provided in initial rendering of the HTML page.

You can look into [our official boilerplate](https://github.com/salsita/redux-boilerplate) we [are doing it](https://github.com/salsita/redux-boilerplate/blob/master/src/client/default/main.js#L59) exactly this way. 

I do not think that `redux-async-initial-state` would help you anyhow since you want to initially load the state synchronously.

Was my explanation any helpful?
