### ISSUE TITLE
redux-elm-boilerplate

### ISSUE THREAD

**Issue by jmarceli** [salsita/redux-elm#33]
Hi,
Based on https://github.com/mxstbr/react-boilerplate which is (probably) one of the most popular redux boilerplates I manage to create similar repo for redux-elm named [redux-elm-boilerplate](https://github.com/jmarceli/redux-elm-boilerplate).

I'm definitely not an expert but I think that my repo might be used as a simple showcase for anyone who is getting started with Elm Architecture in Redux. I've provided all the features available in original react-boilerplate but implemented according to the redux-elm (with some IMO necessary modifications).

Getting any feedback is more than welcome.

**Comment by tomkis1** [comment]
Hello!

Thanks @jmarceli, your contribution is much appreciated.

We actually have quite robust boilerplate already, (will mention that in readme and docs in next release). You may find it [here](https://github.com/salsita/redux-boilerplate), we basically wanted to have a boilerplate which supports:

- `react-native`
- `react`
- server side render
- hot reloading & redux tooling
- routing

We didn't care too much about stuff like CSS and theming though so I believe this is definitely part where your boilerplate is more powerful.

Would you be willing looking into that and discussing what can be (should be) improved/reduced?

The idea is that we would have one official boilerplate which anyone could use but we don't want to fork current stuff like `redux-boilerplate` or `react-boilerplate` since `redux-elm` does not suit that well with idiomatic `redux`.

**Comment by jmarceli** [comment]
The boilerplate which I've published is just a part/base for my app (which I decided to build on top of `redux-elm`). I've needed simple only client-side app (used as Rails API client), because as for now I have no option to support server side rendering nor react-native (that's why I didn't use your boilerplate).
My main goal is to integrate redux-form and react-router-redux with redux-elm. I'll continue to update my repo and after finishing my app I'll check if any of mine solutions might be applicable for `redux-boilerplate`.

Mean while I'm also updating my [redux-elm-form](https://github.com/jmarceli/redux-elm-form) and [redux-elm-router](https://github.com/jmarceli/redux-elm-router) examples. I might turn them into documentation chapters if you will find them useful.

**Comment by tomkis1** [comment]
Oh I didn't mean to discourage you! I mean you did really great job and I would be really happy if you kept working on `redux-elm-boilerplate` because that's something what will eventually people really need.

Anyway, feel free to mention me in any issue filed in your repo so that we can consolidate the effort.

**Comment by jmarceli** [comment]
OK. I'll probably do that as soon as I have some more time to work on it. The first "improvement" I'm planning to do is running a demo somewhere (maybe on Heroku) because IMO that's the easiest way to show what to expect from boilerplate code.

**Comment by tomkis1** [comment]
will be mentioned in v3.1.0 https://github.com/salsita/redux-elm/tree/next#boilerplate
